### ISSUE TITLE
Bug on /social_stats/main/index

### ISSUE THREAD

**Issue by marc-farre** [petersphilo/humhub-social_stats#9]
Message:

```
yii\base\ErrorException: Array to string conversion in /var/www/hhdev/protected/modules/social_stats/views/main/index.php:345
Stack trace:
#0 /var/www/hhdev/protected/modules/social_stats/views/main/index.php(345): yii\web\ErrorHandler->handleError(code: '...', message: '...', file: '...', line: '...')
#1 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(347): humhub\modules\ui\view\components\View->unknown()
#2 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(257): humhub\modules\ui\view\components\View->renderPhpFile(_file_: '...', _params_: '...')
#3 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/View.php(156): humhub\modules\ui\view\components\View->renderFile(viewFile: '...', params: '...', context: '...')
#4 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Controller.php(407): humhub\modules\ui\view\components\View->render(view: '...', params: '...', context: '...')
#5 /var/www/hhdev/protected/modules/social_stats/controllers/MainController.php(44): humhub\modules\social_stats\controllers\MainController->render(view: '...', params: '...')
#6 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): humhub\modules\social_stats\controllers\MainController->actionIndex()
#7 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/var/www/hhdev/protected/vendor/yiisoft/yii2/base/InlineAction.php:57}(callback: '...', args: '...')
#8 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(params: '...')
#9 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Module.php(552): humhub\modules\social_stats\controllers\MainController->runAction(id: '...', params: '...')
#10 /var/www/hhdev/protected/vendor/yiisoft/yii2/web/Application.php(103): humhub\components\Application->runAction(route: '...', params: '...')
#11 /var/www/hhdev/protected/vendor/yiisoft/yii2/base/Application.php(384): humhub\components\Application->handleRequest(request: '...')
#12 /var/www/hhdev/index.php(25): humhub\components\Application->run()
#13 {main}
```

**Comment by petersphilo** [comment]
Hello There,

Would it be possible to provide a little context on this?

There is no line 345 in the file in question; maybe an altered version?

**Comment by marc-farre** [comment]
OK, I understand the reason. This is because I'm working with @ArchBlood version. The bug is here: https://github.com/ArchBlood/humhub-social_stats/blob/873f6beab2b7fe1f5b13b9dae379ed77b9f2c8f4/views/main/index.php#L233

I close this issue and continue the discussion on https://github.com/petersphilo/humhub-social_stats/issues/2
